In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
  'the glass of milk',
  'the glass of juice',
  'the cup of tea',
  'I am a good girl',
  'I am a good developer',
  'Understant the meaning of words',
  'I am very very good'
]

In [3]:
# Define the vacabulary size
voc_size = 10000

In [4]:
# One hot representation 
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[4643, 5659, 1118, 5456],
 [4643, 5659, 1118, 4886],
 [4643, 4805, 1118, 793],
 [9935, 8913, 2198, 2725, 4511],
 [9935, 8913, 2198, 2725, 6586],
 [6799, 4643, 3335, 1118, 9350],
 [9935, 8913, 1230, 1230, 2725]]

In [5]:
# word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [6]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding="pre", maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4643 5659 1118 5456]
 [   0    0    0    0 4643 5659 1118 4886]
 [   0    0    0    0 4643 4805 1118  793]
 [   0    0    0 9935 8913 2198 2725 4511]
 [   0    0    0 9935 8913 2198 2725 6586]
 [   0    0    0 6799 4643 3335 1118 9350]
 [   0    0    0 9935 8913 1230 1230 2725]]


In [7]:
# feature representation
dim = 10

In [8]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_shape = (sent_length,)))
model.compile('adam', 'mse')

c:\Users\91842\Desktop\GenAI\venv\Lib\site-packages\keras\src\layers\core\embedding.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[[ 0.01713052, -0.02741425, -0.02481133,  0.00018018,
          0.04713776,  0.02632909, -0.00059338,  0.02217874,
         -0.00285395, -0.01521232],
        [ 0.01713052, -0.02741425, -0.02481133,  0.00018018,
          0.04713776,  0.02632909, -0.00059338,  0.02217874,
         -0.00285395, -0.01521232],
        [ 0.01713052, -0.02741425, -0.02481133,  0.00018018,
          0.04713776,  0.02632909, -0.00059338,  0.02217874,
         -0.00285395, -0.01521232],
        [ 0.01713052, -0.02741425, -0.02481133,  0.00018018,
          0.04713776,  0.02632909, -0.00059338,  0.02217874,
         -0.00285395, -0.01521232],
        [-0.01372596,  0.03405834, -0.014341  ,  0.02797512,
          0.01174787, -0.00606899, -0.00518186, -0.0220398 ,
          0.04887447, -0.02860808],
        [ 0.03208986,  0.0384025 , -0.02144312,  0.00331501,
          0.00407318,  0.03279996, -0.02474587, -0.01911753,
          0.0428426 , -0.01467161],
        [ 0.03509319,  0.03401447, -0.01621259,  0.0

In [13]:
embedded_docs[0]
prediction =  model.predict(np.array([embedded_docs[0]]))
print(prediction.shape)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
(1, 8, 10)
